name: sound_flow
description: "SoulSound: A sleek, offline local music player for Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Local Persistence
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Audio
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  
  # Metadata & File
  flutter_media_metadata: ^1.0.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  path: ^1.9.0
  file_picker: ^8.0.0

  # Utils
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0 # For premium typography
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#121212" # Dark background matches app theme
  image: "assets/images/android/main_screen_logo.png"

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/android/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/ios/
    - assets/images/android/
